import { Lexend } from "next/font/google";
import "./globals.css";



const getLexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${getLexend.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
